#!/bin/bash

SRC_FILE=datasets/test/source_test.txt
STORE=predictions/
BEAM=5

MIN=5
MAX=120
ALPHA=0.01

MODELS_DIR=/home/eleni/Documents/MetaTrans/models/


for model_id in {1,2,3,4,5,6}
do
	MODEL_FILE=MODELS_DIR'/model_'$model_id'.pt'
	OUT_NAME='model_'$model_id'_beam'$beam'.txt'
	OUT_FILE=$STORE$OUT_NAME
	python translate.py -model $MODEL_FILE -src $SRC_FILE -output $OUT_FILE -n_best $BEAM -beam_size $BEAM -verbose -min_length $MIN -max_length $MAX 
done

